version: '3'

volumes:
    static_volume: {}

services:
    backend:
        restart: unless-stopped
        build: ./backend
        env_file:
          - .env
        volumes:
            - ./backend:/app/backend
            - static_volume:/app/backend/django_static
        expose:
            - 8000    
    nginx: 
        restart: unless-stopped
        build: ./frontend
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/django_static
            - ./nginx/development:/etc/nginx/conf.d
        depends_on: 
            - backend

