version: '2'

services:
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        volumes:
            - static_volume:/app/backend/django_static
        expose:
            - 8000      
    nginx: 
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_volume:/app/backend/django_static
            - ./nginx/production:/etc/nginx/conf.d
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        depends_on: 
            - backend
    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"       
  

volumes:
    static_volume: